name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the base Docker 
      working-directory: ./dockerfiles/learn2code_base
      run: docker build . --file Dockerfile --tag benniwi/learn2code:base
    - name: Build the base marp Docker 
      working-directory: ./dockerfiles/learn2code_base_marp
      run: docker build . --file Dockerfile --tag benniwi/learn2code:base_marp
    - name: Build the lecture Docker 
      working-directory: ./dockerfiles/learn2code_lecture
      run: docker build . --file Dockerfile --tag benniwi/learn2code:lecture
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: docker push base
      run: docker push benniwi/learn2code:base
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: docker push base_marp
      run: docker push benniwi/learn2code:base_marp
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: docker push lecture
      run: docker push benniwi/learn2code:lecture
      if: ${{ github.ref == 'refs/heads/main' }}
