name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the base Docker 
      working-directory: ./dockerfiles/learn2code_base
      run: docker build . --file Dockerfile --tag learn2code:base
    - name: Build the lecture Docker 
      working-directory: ./dockerfiles/learn2code_lecture
      run: docker build . --file Dockerfile --tag learn2code:lecture
